# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "f0de29fac09a5286c758d355ea9c82006133a103"

[[deps.JLX]]
path = "."
uuid = "3262f8d0-daab-4fb2-aac9-9bdcd9f9c3f1"
version = "1.0.0"

[[deps.JLXSyntax]]
git-tree-sha1 = "2046b8455589aad7879851007c56ddec3e961068"
repo-rev = "master"
repo-url = "https://github.com/synt7x/JLXSyntax.jl"
uuid = "07bf817f-78d3-4ea8-a096-43d36d7ce150"
version = "1.0.0"
